import './globals.css'
import Navbar from '@/components/Navbar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import ContextProvider from '@/context/ContextProvider'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider> 
          <Navbar /> 
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
